<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class FileElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'accept',
        'addClass',
        'addClasses',
        'after',
        'auto',
        'before',
        'between',
        'clickable',
        'columns',
        'default',
        'description',
        'disabled',
        'displayErrors',
        'drop',
        'fieldName',
        'formatData',
        'formatLoad',
        'info',
        'infoPosition',
        'inline',
        'label',
        'messages',
        'methods',
        'overrideClass',
        'overrideClasses',
        'params',
        'presets',
        'previewUrl',
        'removeClass',
        'removeClasses',
        'removeEndpoint',
        'removeTempEndpoint',
        'replaceClass',
        'replaceClasses',
        'rules',
        'size',
        'slots',
        'softRemove',
        'submit',
        'templates',
        'uploadTempEndpoint',
        'url',
        'urls',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'aria',
        'busy',
        'canRemove',
        'canSelect',
        'canUploadTemp',
        'classes',
        'data',
        'dataPath',
        'dirty',
        'empty',
        'error',
        'errors',
        'filename',
        'hasLabel',
        'hasUploadError',
        'hidden',
        'input',
        'invalid',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isRequired',
        'link',
        'messageBag',
        'model',
        'pending',
        'preparing',
        'preview',
        'progress',
        'removing',
        'requestData',
        'size',
        'stage',
        'uploaded',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'error',
        'remove',
        'reset',
    ];

    protected static array $allowedSlotAttributes = [
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
