<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class LocationElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'addClass',
        'addClasses',
        'addons',
        'after',
        'attrs',
        'before',
        'between',
        'columns',
        'debounce',
        'default',
        'description',
        'disabled',
        'displayErrors',
        'displayKey',
        'extendOptions',
        'fieldName',
        'floating',
        'formatData',
        'formatLoad',
        'info',
        'infoPosition',
        'inline',
        'label',
        'messages',
        'overrideClass',
        'overrideClasses',
        'placeholder',
        'presets',
        'provider',
        'readonly',
        'removeClass',
        'removeClasses',
        'replaceClass',
        'replaceClasses',
        'rules',
        'size',
        'slots',
        'submit',
        'templates',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'aria',
        'busy',
        'classes',
        'data',
        'dataPath',
        'debouncing',
        'defaultOptions',
        'dirty',
        'empty',
        'error',
        'errors',
        'focused',
        'hasFloating',
        'hasLabel',
        'hidden',
        'input',
        'invalid',
        'isDanger',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isReadonly',
        'isRequired',
        'isSuccess',
        'location',
        'locationService',
        'messageBag',
        'model',
        'pending',
        'placeholder',
        'requestData',
        'size',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'reset',
    ];

    protected static array $allowedSlotAttributes = [
        'addon-after' => [],
        'addon-before' => [],
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
