<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class MultifileElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'accept',
        'addClass',
        'addClasses',
        'after',
        'auto',
        'before',
        'between',
        'clickable',
        'columns',
        'controls',
        'default',
        'description',
        'disabled',
        'displayErrors',
        'drop',
        'fieldName',
        'fields',
        'file',
        'formatData',
        'formatLoad',
        'info',
        'infoPosition',
        'inline',
        'label',
        'messages',
        'object',
        'order',
        'orderBy',
        'overrideClass',
        'overrideClasses',
        'params',
        'presets',
        'previewUrl',
        'removeClass',
        'removeClasses',
        'removeEndpoint',
        'removeTempEndpoint',
        'replaceClass',
        'replaceClasses',
        'rules',
        'size',
        'slots',
        'softRemove',
        'sort',
        'storeFile',
        'storeOrder',
        'submit',
        'templates',
        'uploadTempEndpoint',
        'url',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'aria',
        'busy',
        'children_',
        'classes',
        'data',
        'dataPath',
        'debouncing',
        'dirty',
        'empty',
        'error',
        'errors',
        'hasAdd',
        'hasLabel',
        'hasRemove',
        'hasSort',
        'hasUploading',
        'hidden',
        'input',
        'invalid',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isRequired',
        'isSortable',
        'messageBag',
        'model',
        'orderByName',
        'pending',
        'preparing',
        'requestData',
        'size',
        'sorting',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
    ];

    protected static array $allowedEventAttributes = [
        'add',
        'change',
        'clear',
        'remove',
        'reset',
        'sort',
    ];

    protected static array $allowedSlotAttributes = [
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
