<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class PhoneElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'addClass',
        'addClasses',
        'after',
        'allowIncomplete',
        'attrs',
        'autocomplete',
        'before',
        'between',
        'columns',
        'debounce',
        'default',
        'description',
        'disabled',
        'displayErrors',
        'exclude',
        'fieldName',
        'floating',
        'formatData',
        'formatLoad',
        'include',
        'info',
        'infoPosition',
        'inline',
        'label',
        'loading',
        'messages',
        'overrideClass',
        'overrideClasses',
        'placeholder',
        'presets',
        'readonly',
        'removeClass',
        'removeClasses',
        'replaceClass',
        'replaceClasses',
        'rules',
        'size',
        'slots',
        'submit',
        'templates',
        'unmask',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'addonOptions',
        'addonPlaceholder',
        'aria',
        'busy',
        'classes',
        'data',
        'dataPath',
        'debouncing',
        'dirty',
        'empty',
        'error',
        'errors',
        'focused',
        'hasFloating',
        'hasLabel',
        'hidden',
        'input',
        'inputType',
        'invalid',
        'isDanger',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isLoading',
        'isReadonly',
        'isRequired',
        'isSuccess',
        'mask',
        'maskPluginInstalled',
        'messageBag',
        'model',
        'options_',
        'pending',
        'placeholder',
        'requestData',
        'size',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
    ];

    protected static array $allowedEventAttributes = [
        'blur',
        'change',
        'clear',
        'close',
        'focus',
        'open',
        'reset',
        'select',
    ];

    protected static array $allowedSlotAttributes = [
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
