<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class SelectElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'addClass' => 'array|object|string|function',
        'addClasses' => 'object|function',
        'addOptionOn' => 'array',
        'after' => 'object|string|number',
        'allowAbsent' => 'boolean',
        'appendNewOption' => 'boolean',
        'appendTo' => 'string',
        'appendToBody' => 'boolean',
        'attrs' => 'object',
        'autocomplete' => 'string',
        'before' => 'object|string|number',
        'between' => 'object|string|number',
        'canClear' => 'boolean',
        'canDeselect' => 'boolean',
        'caret' => 'boolean',
        'clearOnRefetch' => 'boolean',
        'clearOnSearch' => 'boolean',
        'closeOnDeselect' => 'boolean',
        'closeOnSelect' => 'boolean',
        'columns' => 'object|string|number',
        'conditions' => 'array',
        'create' => 'boolean',
        'dataKey' => 'string',
        'default' => 'string|number|object',
        'delay' => 'number',
        'description' => 'string|object',
        'disabled' => 'boolean|function|array|object',
        'displayErrors' => 'boolean',
        'extendOptions' => 'object',
        'fieldName' => 'string|object',
        'filterResults' => 'boolean',
        'floating' => 'string|boolean|object',
        'formatData' => 'function',
        'formatLoad' => 'function',
        'groupHideEmpty' => 'boolean',
        'groupLabel' => 'string',
        'groupOptions' => 'string',
        'groups' => 'boolean',
        'id' => 'string',
        'info' => 'string|object',
        'infoPosition' => 'string',
        'inline' => 'boolean',
        'inputType' => 'string',
        'items' => 'object|array|function|string',
        'label' => 'string|object|function',
        'labelProp' => 'string',
        'limit' => 'number',
        'loading' => 'boolean',
        'messages' => 'object',
        'minChars' => 'number',
        'name' => 'string|number',
        'native' => 'boolean',
        'noOptionsText' => 'string|object',
        'noResultsText' => 'string|object',
        'object' => 'boolean',
        'openDirection' => 'string',
        'overrideClass' => 'array|object|string|function',
        'overrideClasses' => 'object|function',
        'placeholder' => 'string|object',
        'presets' => 'array',
        'removeClass' => 'array|object|function',
        'removeClasses' => 'object|function',
        'replaceClass' => 'object|function',
        'replaceClasses' => 'object|function',
        'resolveOnLoad' => 'boolean',
        'rules' => 'array|string|object',
        'search' => 'boolean',
        'searchParam' => 'string',
        'size' => 'string',
        'slots' => 'object',
        'strict' => 'boolean',
        'submit' => 'boolean',
        'templates' => 'object',
        'trackBy' => 'string|array',
        'truncate' => 'boolean',
        'valueProp' => 'string',
        'view' => 'string',
        'views' => 'object',
    ];

    protected static array $allowedProperties = [
        'aria' => 'object',
        'available' => 'boolean',
        'busy' => 'boolean',
        'classes' => 'object',
        'container' => 'HTMLElement',
        'data' => 'object',
        'dataPath' => 'string',
        'dirty' => 'boolean',
        'el_' => 'VueformElement',
        'empty' => 'boolean',
        'error' => 'string',
        'errors' => 'array',
        'fieldId' => 'string',
        'focused' => 'boolean',
        'form_' => 'Vueform',
        'hasFloating' => 'boolean',
        'hasLabel' => 'boolean',
        'hidden' => 'boolean',
        'input' => 'HTMLElement',
        'invalid' => 'boolean',
        'isDanger' => 'boolean',
        'isDefault' => 'boolean',
        'isDisabled' => 'boolean',
        'isFilled' => 'boolean',
        'isLoading' => 'boolean',
        'isRequired' => 'boolean',
        'isSuccess' => 'boolean',
        'messageBag' => 'MessageBag',
        'model' => 'any',
        'mounted' => 'boolean',
        'parent' => 'VNode',
        'path' => 'string',
        'pending' => 'boolean',
        'placeholder' => 'string',
        'requestData' => 'object',
        'resolvedOptions' => 'array',
        'size' => 'string',
        'template' => 'object',
        'theme' => 'object',
        'useCustomFilled' => 'boolean',
        'validated' => 'boolean',
        'value' => 'any',
        'view' => 'string',
        'visible' => 'boolean',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'close',
        'deselect',
        'open',
        'paste',
        'reset',
        'search-change',
        'select',
    ];

    protected static array $allowedSlotAttributes = [
        'after' => [],
        'after-list' => [],
        'before' => [],
        'before-list' => [],
        'between' => [],
        'caret' => [],
        'clear' => [],
        'description' => [],
        'group-label' => [],
        'info' => [],
        'label' => [],
        'no-options' => [],
        'no-results' => [],
        'option' => [],
        'placeholder' => [],
        'required' => [],
        'single-label' => [],
        'spinner' => [],
    ];
}
