<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class SignatureElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'accept',
        'addClass',
        'addClasses',
        'after',
        'autoload',
        'before',
        'between',
        'canClear',
        'canDrop',
        'canUndo',
        'colors',
        'columns',
        'debounce',
        'default',
        'description',
        'disabled',
        'displayErrors',
        'fieldName',
        'fonts',
        'formatData',
        'formatLoad',
        'height',
        'info',
        'infoPosition',
        'inline',
        'invertColors',
        'label',
        'line',
        'maxFontSize',
        'maxSize',
        'maxWidth',
        'messages',
        'minFontSize',
        'modes',
        'overrideClass',
        'overrideClasses',
        'placeholder',
        'presets',
        'readonly',
        'removeClass',
        'removeClasses',
        'replaceClass',
        'replaceClasses',
        'rules',
        'size',
        'slots',
        'submit',
        'templates',
        'uploadHeight',
        'uploadWidth',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'aria',
        'busy',
        'classes',
        'clearAriaLabel',
        'color',
        'colorAriaLabel',
        'created',
        'creating',
        'data',
        'dataPath',
        'dirty',
        'dndText',
        'dragging',
        'drawing',
        'drawn',
        'droppable',
        'empty',
        'error',
        'errors',
        'fileAccept',
        'file_',
        'focused',
        'fontFamilies',
        'fontFamily',
        'fontSelectorAria',
        'fontSize',
        'fontText',
        'fontWeight',
        'fontWeights',
        'font_',
        'hasLabel',
        'hidden',
        'image',
        'imgAltText',
        'imgTitleText',
        'input',
        'inputAriaLabel',
        'inputStyle',
        'input_',
        'invalid',
        'isDanger',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isReadonly',
        'isRequired',
        'isSuccess',
        'lastWidth',
        'lineStyle',
        'messageBag',
        'mode',
        'modeSelectorAria',
        'mode_',
        'model',
        'pad',
        'padAriaLabel',
        'padHeight',
        'padStyle',
        'padWidth',
        'pad_',
        'pending',
        'placeholder',
        'placeholderText',
        'preview_',
        'processing',
        'redoText',
        'redos',
        'requestData',
        'resolvedFonts',
        'resolvedModes',
        'showClear',
        'showColors',
        'showFonts',
        'showInput',
        'showLine',
        'showModes',
        'showPad',
        'showPlaceholder',
        'showPreview',
        'showUndos',
        'showUpload',
        'showUploadContainer',
        'size',
        'tabindex',
        'text',
        'undoText',
        'undosLeft',
        'uploadButtonText',
        'uploadButton_',
        'upload_',
        'uploaded',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
        'width',
        'wrapperAriaLabel',
        'wrapperStyle',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'reset',
    ];

    protected static array $allowedSlotAttributes = [
        'addon-after' => [],
        'addon-before' => [],
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
