<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class SignatureElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'accept' => 'array',
        'addClass' => 'array|object|string|function',
        'addClasses' => 'object|function',
        'after' => 'object|string|number',
        'autoload' => 'boolean',
        'before' => 'object|string|number',
        'between' => 'object|string|number',
        'canClear' => 'boolean',
        'canDrop' => 'boolean',
        'canUndo' => 'boolean',
        'colors' => 'array',
        'columns' => 'object|string|number',
        'conditions' => 'array',
        'debounce' => 'number',
        'default' => 'string|number|object',
        'description' => 'string|object',
        'disabled' => 'boolean|function|array|object',
        'displayErrors' => 'boolean',
        'fieldName' => 'string|object',
        'fonts' => 'array',
        'formatData' => 'function',
        'formatLoad' => 'function',
        'height' => 'number',
        'id' => 'string',
        'info' => 'string|object',
        'infoPosition' => 'string',
        'inline' => 'boolean',
        'invertColors' => 'array',
        'label' => 'string|object|function',
        'line' => 'boolean',
        'maxFontSize' => 'number',
        'maxSize' => 'number',
        'maxWidth' => 'number|string',
        'messages' => 'object',
        'minFontSize' => 'number',
        'modes' => 'array',
        'name' => 'string|number',
        'overrideClass' => 'array|object|string|function',
        'overrideClasses' => 'object|function',
        'placeholder' => 'string|object|boolean',
        'presets' => 'array',
        'readonly' => 'boolean|function|array|object',
        'removeClass' => 'array|object|function',
        'removeClasses' => 'object|function',
        'replaceClass' => 'object|function',
        'replaceClasses' => 'object|function',
        'rules' => 'array|string|object',
        'size' => 'string',
        'slots' => 'object',
        'submit' => 'boolean',
        'templates' => 'object',
        'uploadHeight' => 'number',
        'uploadWidth' => 'number',
        'view' => 'string',
        'views' => 'object',
    ];

    protected static array $allowedProperties = [
        'aria' => 'object',
        'available' => 'boolean',
        'busy' => 'boolean',
        'classes' => 'object',
        'clearAriaLabel' => 'string',
        'color' => 'string',
        'colorAriaLabel' => 'string',
        'container' => 'HTMLElement',
        'created' => 'boolean',
        'creating' => 'boolean',
        'data' => 'object',
        'dataPath' => 'string',
        'dirty' => 'boolean',
        'dndText' => 'string',
        'dragging' => 'boolean',
        'drawing' => 'boolean',
        'drawn' => 'boolean',
        'droppable' => 'boolean',
        'el_' => 'VueformElement',
        'empty' => 'boolean',
        'error' => 'string',
        'errors' => 'array',
        'fieldId' => 'string',
        'fileAccept' => 'string',
        'file_' => 'HTMLInputElement',
        'focused' => 'boolean',
        'fontFamilies' => 'array',
        'fontFamily' => 'string',
        'fontSelectorAria' => 'object',
        'fontSize' => 'number',
        'fontText' => 'string',
        'fontWeight' => 'string',
        'fontWeights' => 'array',
        'font_' => 'ElementAddonOptions',
        'form_' => 'Vueform',
        'hasLabel' => 'boolean',
        'hidden' => 'boolean',
        'image' => 'File',
        'imgAltText' => 'string',
        'imgTitleText' => 'string',
        'input' => 'HTMLElement',
        'inputAriaLabel' => 'string',
        'inputStyle' => 'object',
        'input_' => 'HTMLInputElement',
        'invalid' => 'boolean',
        'isDanger' => 'boolean',
        'isDefault' => 'boolean',
        'isDisabled' => 'boolean',
        'isFilled' => 'boolean',
        'isReadonly' => 'boolean',
        'isRequired' => 'boolean',
        'isSuccess' => 'boolean',
        'lastWidth' => 'number',
        'lineStyle' => 'object',
        'messageBag' => 'MessageBag',
        'mode' => 'string',
        'modeSelectorAria' => 'object',
        'mode_' => 'ElementAddonOptions',
        'model' => 'any',
        'mounted' => 'boolean',
        'pad' => 'object',
        'padAriaLabel' => 'string',
        'padHeight' => 'number',
        'padStyle' => 'object',
        'padWidth' => 'number',
        'pad_' => 'HTMLCanvasElement',
        'parent' => 'VNode',
        'path' => 'string',
        'pending' => 'boolean',
        'placeholder' => 'string',
        'placeholderText' => 'string',
        'preview_' => 'HTMLCanvasElement',
        'processing' => 'boolean',
        'redoText' => 'string',
        'redos' => 'array',
        'requestData' => 'object',
        'resolvedFonts' => 'array',
        'resolvedModes' => 'array',
        'showClear' => 'boolean',
        'showColors' => 'boolean',
        'showFonts' => 'boolean',
        'showInput' => 'boolean',
        'showLine' => 'boolean',
        'showModes' => 'boolean',
        'showPad' => 'boolean',
        'showPlaceholder' => 'boolean',
        'showPreview' => 'boolean',
        'showUndos' => 'boolean',
        'showUpload' => 'boolean',
        'showUploadContainer' => 'boolean',
        'size' => 'string',
        'tabindex' => 'number|undefined',
        'template' => 'object',
        'text' => 'string',
        'theme' => 'object',
        'undoText' => 'string',
        'undosLeft' => 'number',
        'uploadButtonText' => 'string',
        'uploadButton_' => 'HTMLElement',
        'upload_' => 'HTMLElement',
        'uploaded' => 'boolean',
        'useCustomFilled' => 'boolean',
        'validated' => 'boolean',
        'value' => 'any',
        'view' => 'string',
        'visible' => 'boolean',
        'width' => 'number',
        'wrapperAriaLabel' => 'string',
        'wrapperStyle' => 'object',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'reset',
    ];

    protected static array $allowedSlotAttributes = [
        'addon-after' => [],
        'addon-before' => [],
        'after' => [],
        'before' => [],
        'between' => [],
        'description' => [],
        'info' => [],
        'label' => [],
        'required' => [],
    ];
}
