<?php

namespace LaravelVueForm\Elements\Fields;

use LaravelVueForm\Builder\FormSchemaBuilder;

class TagsElement extends FormSchemaBuilder
{
    protected static array $allowedAttributes = [
        'addClass',
        'addClasses',
        'addOptionOn',
        'after',
        'allowAbsent',
        'appendNewOption',
        'appendTo',
        'appendToBody',
        'attrs',
        'autocomplete',
        'before',
        'between',
        'breakTags',
        'canClear',
        'caret',
        'clearOnRefetch',
        'clearOnSearch',
        'clearOnSelect',
        'closeOnDeselect',
        'closeOnSelect',
        'columns',
        'create',
        'dataKey',
        'default',
        'delay',
        'description',
        'disabled',
        'displayErrors',
        'extendOptions',
        'fieldName',
        'filterResults',
        'floating',
        'formatData',
        'formatLoad',
        'groupHideEmpty',
        'groupLabel',
        'groupOptions',
        'groupSelect',
        'groups',
        'hideSelected',
        'info',
        'infoPosition',
        'inline',
        'inputType',
        'items',
        'label',
        'labelProp',
        'limit',
        'loading',
        'max',
        'messages',
        'minChars',
        'noOptionsText',
        'noResultsText',
        'object',
        'openDirection',
        'overrideClass',
        'overrideClasses',
        'placeholder',
        'presets',
        'removeClass',
        'removeClasses',
        'replaceClass',
        'replaceClasses',
        'resolveOnLoad',
        'rules',
        'search',
        'searchParam',
        'showOptions',
        'size',
        'slots',
        'strict',
        'submit',
        'templates',
        'trackBy',
        'valueProp',
        'view',
        'views',
    ];

    protected static array $allowedProperties = [
        'aria',
        'busy',
        'classes',
        'dataPath',
        'dirty',
        'empty',
        'error',
        'errors',
        'focused',
        'hasFloating',
        'hasLabel',
        'hidden',
        'input',
        'invalid',
        'isDanger',
        'isDefault',
        'isDisabled',
        'isFilled',
        'isLoading',
        'isRequired',
        'isSuccess',
        'messageBag',
        'model',
        'pending',
        'placeholder',
        'resolvedOptions',
        'size',
        'useCustomFilled',
        'validated',
        'value',
        'view',
        'visible',
    ];

    protected static array $allowedEventAttributes = [
        'change',
        'clear',
        'close',
        'deselect',
        'open',
        'paste',
        'reset',
        'search-change',
        'select',
        'tag',
    ];

    protected static array $allowedSlotAttributes = [
        'after' => [],
        'after-list' => [],
        'before' => [],
        'before-list' => [],
        'between' => [],
        'caret' => [],
        'clear' => [],
        'description' => [],
        'disabled' => [],
        'group-label' => [],
        'handleTagRemove' => [],
        'info' => [],
        'label' => [],
        'no-options' => [],
        'no-results' => [],
        'option' => [],
        'placeholder' => [],
        'required' => [],
        'spinner' => [],
        'tag' => [],
    ];
    
    protected function items(array|string $data): static
    {
        $this->attributes['items'] = $data;
        return $this;
    }
}
